version: '2'
services:
  nifi:
    image: mkobit/nifi
    hostname: nifi
    ulimits:
      nproc: 65535
      nofile:
        soft: 60000
        hard: 60000
    ports:
      - "2202:22"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./conf/hdfs:/opt/hdfs:ro
    links:
      - hdfs
  hdfs:
    image: minyk/hdfs-daemon
    hostname: hdfs
    ports:
      - "2203:22"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "8020:8020"
    ulimits:
      nproc: 65535
      nofile:
        soft: 60000
        hard: 60000
